[env]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps =
  bodmer/TFT_eSPI
  PaulStoffregen/XPT2046_Touchscreen
build_flags =
  -D USER_SETUP_LOADED=1
  -D ILI9488_DRIVER=1
  -D TFT_WIDTH=480
  -D TFT_HEIGHT=320
  -D TFT_MOSI=23
  -D TFT_SCLK=18
  -D TFT_MISO=19
  -D TFT_CS=15
  -D TFT_DC=2
  -D TFT_RST=4
  -D TOUCH_CS=21
  -D SPI_FREQUENCY=40000000
  -D SPI_TOUCH_FREQUENCY=2000000

[env:test]
src_filter = +<../src/test/*>

[env:probe]
src_filter = +<../src/probe/*>
